### ISSUE TITLE
Error when using Int instead of Float as a rotation angle

### ISSUE THREAD

**Issue by tjjarvinen** [FugroRoames/Rotations.jl#107] opened 2020-01-24 17:37 UTC
```julia
using Rotations

# This works
RotX(1.0)*rand(3,5)

# This does not
RotX(1)*rand(3,5)
```

I get this error
```julia
ERROR: InexactError: Int64(0.5403023058681398)
Stacktrace:
 [1] Int64 at ./float.jl:709 [inlined]
 [2] convert at ./number.jl:7 [inlined]
 [3] setindex! at ./array.jl:784 [inlined]
 [4] copy_transpose!(::Array{Int64,2}, ::UnitRange{Int64}, ::UnitRange{Int64}, ::RotX{Int64}, ::UnitRange{Int64}, ::UnitRange{Int64}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/LinearAlgebra/src/transpose.jl:197
 [5] copy_transpose! at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/LinearAlgebra/src/matmul.jl:589 [inlined]
 [6] _generic_matmatmul!(::Array{Float64,2}, ::Char, ::Char, ::RotX{Int64}, ::Array{Float64,2}, ::LinearAlgebra.MulAddMul{true,true,Bool,Bool}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/LinearAlgebra/src/matmul.jl:730
 [7] generic_matmatmul!(::Array{Float64,2}, ::Char, ::Char, ::RotX{Int64}, ::Array{Float64,2}, ::LinearAlgebra.MulAddMul{true,true,Bool,Bool}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/LinearAlgebra/src/matmul.jl:694
 [8] mul! at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/LinearAlgebra/src/matmul.jl:230 [inlined]
 [9] mul! at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/LinearAlgebra/src/matmul.jl:203 [inlined]
 [10] *(::RotX{Int64}, ::Array{Float64,2}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/LinearAlgebra/src/matmul.jl:153
 [11] top-level scope at REPL[2]:1
```

```julia
julia> versioninfo()
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen Threadripper 1950X 16-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, znver1)
```

**Comment by tkoolen** [comment] 2020-01-24 18:05
Duplicate of https://github.com/FugroRoames/Rotations.jl/issues/55.

**Closed by tkoolen** 2020-01-24 18:05 UTC
